baseURL = 'https://kenjiusui.github.io/blog/'
locale = 'ja'
title = 'my blog'
theme = "PaperMod"
metaDataFormat = 'yaml'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 20

[[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 30
