baseURL = 'https://kenjiusui.github.io/blog/'
locale = 'ja'
title = 'Think and Write'
theme = "PaperMod"
metaDataFormat = 'yaml'

[params]
  defaultTheme = "auto"
  ShowReadingTime = false
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [params.profileMode]
    enabled = true
    title = "考えたら書く"

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "books"
  name = "Book"
  url = "/books/"
  weight = 15

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 5
